// GENERATED by scripts/gen-doms-swift.mjs — DO NOT EDIT BY HAND.
//
// Source of truth:
//   · DOMS_MUSCLES, DOMS_LEVELS           scripts/src/soreness.ts
//   · DOMS_TO_LANDMARK                    scripts/src/atlas.ts
//   · SUB_REGIONS, JOINTS, SORENESS_SIDES scripts/src/subRegions.ts
//
// Re-run `npm run doms` after changing any of those. `npm run check:doms`
// fails if this file is stale, and it is part of `npm run check`.

import OnyxCore

/// The soreness vocabularies, mirrored from the web.
///
/// The GROUP is what a user rates (a sore arm is a sore arm); the landmarks are
/// what the figure draws; the sub-region is optional detail the scoring engine
/// never reads. Severity 0…3 becomes intensity 0…1 because the atlas draws
/// AMOUNT and passes no verdicts.
enum DomsMap {

    /// Every list comes from `DomsMuscles` in OnyxCore — one vocabulary, and
    /// the scorer's copy is the one that exists. These are the names the views
    /// and their tests already call.
    static let muscles = DomsMuscles.all
    static let levels = DomsMuscles.levels
    static let maxSeverity = DomsMuscles.maxSeverity
    static let sides = DomsMuscles.sides
    static let joints = DomsMuscles.joints
    static let subRegions = DomsMuscles.subRegions
    static let parentOfSubRegion = DomsMuscles.parentOfSubRegion

    static let landmarks: [String: [LandmarkMuscle]] = [
        "Chest": [.chest],
        "Back": [.lats, .upperBack, .lowerBack],
        "Arms": [.biceps, .triceps, .forearms],
        "Shoulders": [.frontDelts, .sideDelts, .rearDelts],
        "Abs": [.absCore],
        "Glutes": [.glutes],
        "Quads": [.quads],
        "Hamstrings": [.hamstrings],
        "Inner thighs": [.adductors],
        "Calves": [.calves],
    ]

    /// `domsToWorked` — group → severity becomes landmark → 0…1, max-merged.
    static func worked(_ severity: [String: Int]) -> [LandmarkMuscle: Double] {
        var out: [LandmarkMuscle: Double] = [:]
        for (muscle, s) in severity where s > 0 {
            let intensity = min(1, max(0, Double(s) / Double(maxSeverity)))
            for landmark in landmarks[muscle] ?? [] {
                out[landmark] = max(out[landmark] ?? 0, intensity)
            }
        }
        return out
    }

    /// "Quads moderate · Chest mild", in display order; nil when nothing is sore.
    static func summary(_ severity: [String: Int]) -> String? {
        let sore = muscles.compactMap { m -> String? in
            guard let s = severity[m], s > 0, s < levels.count else { return nil }
            return "\(m) \(levels[s].lowercased())"
        }
        return sore.isEmpty ? nil : sore.joined(separator: " · ")
    }
}

extension DomsMap {
    /// The group a landmark belongs to — the reverse of `landmarks`, which is
    /// what a tap on the body needs: the atlas answers in landmarks (sixteen)
    /// and soreness is rated in groups (ten).
    static let groupOfLandmark: [LandmarkMuscle: String] = landmarks.reduce(into: [:]) { out, pair in
        for landmark in pair.value { out[landmark] = pair.key }
    }

    static func group(of landmark: LandmarkMuscle) -> String? { groupOfLandmark[landmark] }
}
