// GENERATED by scripts/gen-doms-swift.mjs — DO NOT EDIT BY HAND.
//
// Source of truth:
//   · DOMS_MUSCLES, DOMS_LEVELS           scripts/src/soreness.ts
//   · DOMS_TO_LANDMARK                    scripts/src/atlas.ts
//   · SUB_REGIONS, JOINTS, SORENESS_SIDES scripts/src/subRegions.ts
//
// Re-run `npm run doms` after changing any of those. `npm run check:doms`
// fails if either file is stale, and it is part of `npm run check`.

import Foundation

/// The soreness vocabulary, mirrored from the web.
///
/// Lives in OnyxCore because the SCORER needs it: `ScoringInputsBuilder` folds a
/// day's rows down to one severity per recognised muscle, and a row whose
/// `muscle_group` is not one of these can never be read back as a rating —
/// counting it would let unreadable data move the battery, which it did.
public enum DomsMuscles {

    /// Display order: upper, trunk, lower — as the web lists them.
    public static let all = ["Chest", "Back", "Arms", "Shoulders", "Abs", "Glutes", "Quads", "Hamstrings", "Inner thighs", "Calves"]

    /// Membership test for the fold. A Set because it is asked per row.
    public static let recognised: Set<String> = Set(all)

    /// Index IS the stored severity.
    public static let levels = ["None", "Mild", "Moderate", "Severe"]

    public static let maxSeverity = 3

    /// Stored `side` values. `both` is the default and the pre-v2 meaning.
    public static let sides = ["both", "left", "right"]

    /// Non-muscle complaint points. Never scored, never a landmark.
    public static let joints = ["Knee", "Hip", "Ankle", "Wrist", "Elbow", "AC joint", "Lumbar junction", "Neck"]

    /// Sub-regions of the muscles that have them. Record-only: nothing in the
    /// scoring path reads a sub-region, by design.
    public static let subRegions: [String: [String]] = [
        "Back": ["Traps", "Rhomboids", "Lats", "Erectors"],
        "Arms": ["Biceps", "Triceps", "Forearms"],
        "Shoulders": ["Front delts", "Side delts", "Rear delts"],
        "Inner thighs": ["Adductors", "Abductors"],
    ]

    /// The muscle a sub-region belongs to — the fold that keeps the ten intact.
    public static let parentOfSubRegion: [String: String] = subRegions.reduce(into: [:]) { out, pair in
        for sub in pair.value { out[sub] = pair.key }
    }
}
