// GENERATED by scripts/gen-mirror-swift.mjs — DO NOT EDIT.
//
// Source: native/schema/supabase.json (introspected 2026-09-10).
// Edit the fixture and re-run `npm run mirror`; `npm run check:mirror`
// fails the build when this file and the fixture disagree.

import Foundation
import GRDB

// MARK: - daily_logs

/// Mirrors `public.daily_logs` (daily). Delta by `updated_at`.
public struct DailyLogRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "daily_logs"

    public var id: String
    public var userId: String
    public var date: String
    public var steps: Int?
    public var waterMl: Double?
    public var sleepMinutes: Int?
    public var carbsG: Double?
    public var proteinG: Double?
    public var fatsG: Double?
    public var weightKg: Double?
    public var leanMassKg: Double?
    public var bmi: Double?
    public var trainingMinutes: Int?
    public var activeEnergy: Double?
    public var bodyFatPct: Double?
    public var standingMinutes: Int?
    public var avgHeartRate: Int?
    public var avgRestHeartRate: Int?
    public var respiratoryRate: Double?
    public var bloodOxygen: Double?
    public var musclePercent: Double?
    public var waterPercent: Double?
    public var boneMineral: Double?
    public var visceralFat: Double?
    public var bmr: Double?
    public var createdAt: Date
    public var updatedAt: Date
    public var hrvMs: Double?
    public var exerciseMinutes: Int?
    public var standHours: Int?
    public var vo2max: Double?
    public var wristTempDelta: Double?
    public var timeInDaylightMin: Int?
    public var effortRating: Int?
    public var mood: Int?
    public var journalMd: String?
    public var distanceM: Double?
    public var proteinPercent: Double?
    public var muscleMassKg: Double?
    public var waterMassKg: Double?
    public var fatMassKg: Double?
    public var boneMineralKg: Double?
    public var proteinMassKg: Double?
    public var fatFreeMassKg: Double?
    public var weighinSkipReason: String?
    public var skeletalMuscleMassKg: Double?
    public var estimatedWaistToHipRatio: Double?
    public var waistCm: Double?
    public var nutritionException: String?
    public var nutritionEstimated: Bool
    public var sleepOnsetTrouble: Bool
    public var sleepInaccurate: Bool?
    public var hrvOvernight: Bool?

    public enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case date
        case steps
        case waterMl = "water_ml"
        case sleepMinutes = "sleep_minutes"
        case carbsG = "carbs_g"
        case proteinG = "protein_g"
        case fatsG = "fats_g"
        case weightKg = "weight_kg"
        case leanMassKg = "lean_mass_kg"
        case bmi
        case trainingMinutes = "training_minutes"
        case activeEnergy = "active_energy"
        case bodyFatPct = "body_fat_pct"
        case standingMinutes = "standing_minutes"
        case avgHeartRate = "avg_heart_rate"
        case avgRestHeartRate = "avg_rest_heart_rate"
        case respiratoryRate = "respiratory_rate"
        case bloodOxygen = "blood_oxygen"
        case musclePercent = "muscle_percent"
        case waterPercent = "water_percent"
        case boneMineral = "bone_mineral"
        case visceralFat = "visceral_fat"
        case bmr
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case hrvMs = "hrv_ms"
        case exerciseMinutes = "exercise_minutes"
        case standHours = "stand_hours"
        case vo2max
        case wristTempDelta = "wrist_temp_delta"
        case timeInDaylightMin = "time_in_daylight_min"
        case effortRating = "effort_rating"
        case mood
        case journalMd = "journal_md"
        case distanceM = "distance_m"
        case proteinPercent = "protein_percent"
        case muscleMassKg = "muscle_mass_kg"
        case waterMassKg = "water_mass_kg"
        case fatMassKg = "fat_mass_kg"
        case boneMineralKg = "bone_mineral_kg"
        case proteinMassKg = "protein_mass_kg"
        case fatFreeMassKg = "fat_free_mass_kg"
        case weighinSkipReason = "weighin_skip_reason"
        case skeletalMuscleMassKg = "skeletal_muscle_mass_kg"
        case estimatedWaistToHipRatio = "estimated_waist_to_hip_ratio"
        case waistCm = "waist_cm"
        case nutritionException = "nutrition_exception"
        case nutritionEstimated = "nutrition_estimated"
        case sleepOnsetTrouble = "sleep_onset_trouble"
        case sleepInaccurate = "sleep_inaccurate"
        case hrvOvernight = "hrv_overnight"
    }

    public init(
        id: String,
        userId: String,
        date: String,
        steps: Int? = nil,
        waterMl: Double? = nil,
        sleepMinutes: Int? = nil,
        carbsG: Double? = nil,
        proteinG: Double? = nil,
        fatsG: Double? = nil,
        weightKg: Double? = nil,
        leanMassKg: Double? = nil,
        bmi: Double? = nil,
        trainingMinutes: Int? = nil,
        activeEnergy: Double? = nil,
        bodyFatPct: Double? = nil,
        standingMinutes: Int? = nil,
        avgHeartRate: Int? = nil,
        avgRestHeartRate: Int? = nil,
        respiratoryRate: Double? = nil,
        bloodOxygen: Double? = nil,
        musclePercent: Double? = nil,
        waterPercent: Double? = nil,
        boneMineral: Double? = nil,
        visceralFat: Double? = nil,
        bmr: Double? = nil,
        createdAt: Date,
        updatedAt: Date,
        hrvMs: Double? = nil,
        exerciseMinutes: Int? = nil,
        standHours: Int? = nil,
        vo2max: Double? = nil,
        wristTempDelta: Double? = nil,
        timeInDaylightMin: Int? = nil,
        effortRating: Int? = nil,
        mood: Int? = nil,
        journalMd: String? = nil,
        distanceM: Double? = nil,
        proteinPercent: Double? = nil,
        muscleMassKg: Double? = nil,
        waterMassKg: Double? = nil,
        fatMassKg: Double? = nil,
        boneMineralKg: Double? = nil,
        proteinMassKg: Double? = nil,
        fatFreeMassKg: Double? = nil,
        weighinSkipReason: String? = nil,
        skeletalMuscleMassKg: Double? = nil,
        estimatedWaistToHipRatio: Double? = nil,
        waistCm: Double? = nil,
        nutritionException: String? = nil,
        nutritionEstimated: Bool,
        sleepOnsetTrouble: Bool,
        sleepInaccurate: Bool? = nil,
        hrvOvernight: Bool? = nil
    ) {
        self.id = id
        self.userId = userId
        self.date = date
        self.steps = steps
        self.waterMl = waterMl
        self.sleepMinutes = sleepMinutes
        self.carbsG = carbsG
        self.proteinG = proteinG
        self.fatsG = fatsG
        self.weightKg = weightKg
        self.leanMassKg = leanMassKg
        self.bmi = bmi
        self.trainingMinutes = trainingMinutes
        self.activeEnergy = activeEnergy
        self.bodyFatPct = bodyFatPct
        self.standingMinutes = standingMinutes
        self.avgHeartRate = avgHeartRate
        self.avgRestHeartRate = avgRestHeartRate
        self.respiratoryRate = respiratoryRate
        self.bloodOxygen = bloodOxygen
        self.musclePercent = musclePercent
        self.waterPercent = waterPercent
        self.boneMineral = boneMineral
        self.visceralFat = visceralFat
        self.bmr = bmr
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.hrvMs = hrvMs
        self.exerciseMinutes = exerciseMinutes
        self.standHours = standHours
        self.vo2max = vo2max
        self.wristTempDelta = wristTempDelta
        self.timeInDaylightMin = timeInDaylightMin
        self.effortRating = effortRating
        self.mood = mood
        self.journalMd = journalMd
        self.distanceM = distanceM
        self.proteinPercent = proteinPercent
        self.muscleMassKg = muscleMassKg
        self.waterMassKg = waterMassKg
        self.fatMassKg = fatMassKg
        self.boneMineralKg = boneMineralKg
        self.proteinMassKg = proteinMassKg
        self.fatFreeMassKg = fatFreeMassKg
        self.weighinSkipReason = weighinSkipReason
        self.skeletalMuscleMassKg = skeletalMuscleMassKg
        self.estimatedWaistToHipRatio = estimatedWaistToHipRatio
        self.waistCm = waistCm
        self.nutritionException = nutritionException
        self.nutritionEstimated = nutritionEstimated
        self.sleepOnsetTrouble = sleepOnsetTrouble
        self.sleepInaccurate = sleepInaccurate
        self.hrvOvernight = hrvOvernight
    }
}

// MARK: - daily_metrics

/// Mirrors `public.daily_metrics` (daily). Delta by `updated_at`.
public struct DailyMetricRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "daily_metrics"

    public var id: String
    public var userId: String
    public var date: String
    public var steps: Int?
    public var activeCal: Int?
    public var restHr: Int?
    public var createdAt: Date
    public var updatedAt: Date

    public enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case date
        case steps
        case activeCal = "active_cal"
        case restHr = "rest_hr"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }

    public init(
        id: String,
        userId: String,
        date: String,
        steps: Int? = nil,
        activeCal: Int? = nil,
        restHr: Int? = nil,
        createdAt: Date,
        updatedAt: Date
    ) {
        self.id = id
        self.userId = userId
        self.date = date
        self.steps = steps
        self.activeCal = activeCal
        self.restHr = restHr
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }
}

// MARK: - daily_scores

/// Mirrors `public.daily_scores` (daily). Windowed on `date`.
public struct DailyScoreRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "daily_scores"

    public var id: String
    public var userId: String
    public var date: String
    public var score: Int
    public var sleepScore: Int?
    public var nutritionScore: Int?
    public var activityScore: Int?
    public var workoutScore: Int?
    public var recoveryScore: Int?
    public var batteryPct: Int?
    public var computedAt: Date
    public var finalized: Bool

    public enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case date
        case score
        case sleepScore = "sleep_score"
        case nutritionScore = "nutrition_score"
        case activityScore = "activity_score"
        case workoutScore = "workout_score"
        case recoveryScore = "recovery_score"
        case batteryPct = "battery_pct"
        case computedAt = "computed_at"
        case finalized
    }

    public init(
        id: String,
        userId: String,
        date: String,
        score: Int,
        sleepScore: Int? = nil,
        nutritionScore: Int? = nil,
        activityScore: Int? = nil,
        workoutScore: Int? = nil,
        recoveryScore: Int? = nil,
        batteryPct: Int? = nil,
        computedAt: Date,
        finalized: Bool
    ) {
        self.id = id
        self.userId = userId
        self.date = date
        self.score = score
        self.sleepScore = sleepScore
        self.nutritionScore = nutritionScore
        self.activityScore = activityScore
        self.workoutScore = workoutScore
        self.recoveryScore = recoveryScore
        self.batteryPct = batteryPct
        self.computedAt = computedAt
        self.finalized = finalized
    }
}

// MARK: - daily_targets

/// Mirrors `public.daily_targets` (daily). Delta by `updated_at`.
public struct DailyTargetRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "daily_targets"

    public var userId: String
    public var date: String
    public var kcal: Int?
    public var proteinG: Int?
    public var carbsG: Int?
    public var fatG: Int?
    public var stepsGoal: Int?
    public var note: String?
    public var updatedAt: Date
    public var profileKey: String?
    public var trackCarbs: Bool
    public var trackFat: Bool

    public enum CodingKeys: String, CodingKey {
        case userId = "user_id"
        case date
        case kcal
        case proteinG = "protein_g"
        case carbsG = "carbs_g"
        case fatG = "fat_g"
        case stepsGoal = "steps_goal"
        case note
        case updatedAt = "updated_at"
        case profileKey = "profile_key"
        case trackCarbs = "track_carbs"
        case trackFat = "track_fat"
    }

    public init(
        userId: String,
        date: String,
        kcal: Int? = nil,
        proteinG: Int? = nil,
        carbsG: Int? = nil,
        fatG: Int? = nil,
        stepsGoal: Int? = nil,
        note: String? = nil,
        updatedAt: Date,
        profileKey: String? = nil,
        trackCarbs: Bool,
        trackFat: Bool
    ) {
        self.userId = userId
        self.date = date
        self.kcal = kcal
        self.proteinG = proteinG
        self.carbsG = carbsG
        self.fatG = fatG
        self.stepsGoal = stepsGoal
        self.note = note
        self.updatedAt = updatedAt
        self.profileKey = profileKey
        self.trackCarbs = trackCarbs
        self.trackFat = trackFat
    }
}

// MARK: - nutrition_entries

/// Mirrors `public.nutrition_entries` (daily). Windowed on `date`.
public struct NutritionEntryRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "nutrition_entries"

    public var id: String
    public var userId: String
    public var hkUuid: String?
    public var loggedAt: Date
    public var date: String
    public var mealType: String?
    public var calories: Double
    public var proteinG: Double
    public var carbsG: Double
    public var fatG: Double
    public var fiberG: Double?
    public var phase: String?
    public var createdAt: Date
    public var targetKcal: Int?
    public var micros: JSONText?

    public enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case hkUuid = "hk_uuid"
        case loggedAt = "logged_at"
        case date
        case mealType = "meal_type"
        case calories
        case proteinG = "protein_g"
        case carbsG = "carbs_g"
        case fatG = "fat_g"
        case fiberG = "fiber_g"
        case phase
        case createdAt = "created_at"
        case targetKcal = "target_kcal"
        case micros
    }

    public init(
        id: String,
        userId: String,
        hkUuid: String? = nil,
        loggedAt: Date,
        date: String,
        mealType: String? = nil,
        calories: Double,
        proteinG: Double,
        carbsG: Double,
        fatG: Double,
        fiberG: Double? = nil,
        phase: String? = nil,
        createdAt: Date,
        targetKcal: Int? = nil,
        micros: JSONText? = nil
    ) {
        self.id = id
        self.userId = userId
        self.hkUuid = hkUuid
        self.loggedAt = loggedAt
        self.date = date
        self.mealType = mealType
        self.calories = calories
        self.proteinG = proteinG
        self.carbsG = carbsG
        self.fatG = fatG
        self.fiberG = fiberG
        self.phase = phase
        self.createdAt = createdAt
        self.targetKcal = targetKcal
        self.micros = micros
    }
}

// MARK: - water_intake

/// Mirrors `public.water_intake` (daily). Windowed on `date`.
public struct WaterIntakeRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "water_intake"

    public var id: String
    public var userId: String
    public var hkUuid: String?
    public var loggedAt: Date
    public var date: String
    public var amountMl: Double
    public var createdAt: Date

    public enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case hkUuid = "hk_uuid"
        case loggedAt = "logged_at"
        case date
        case amountMl = "amount_ml"
        case createdAt = "created_at"
    }

    public init(
        id: String,
        userId: String,
        hkUuid: String? = nil,
        loggedAt: Date,
        date: String,
        amountMl: Double,
        createdAt: Date
    ) {
        self.id = id
        self.userId = userId
        self.hkUuid = hkUuid
        self.loggedAt = loggedAt
        self.date = date
        self.amountMl = amountMl
        self.createdAt = createdAt
    }
}

// MARK: - supplement_log

/// Mirrors `public.supplement_log` (daily). Delta by `updated_at`.
public struct SupplementLogRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "supplement_log"

    public var userId: String
    public var date: String
    public var itemKey: String
    public var taken: Bool
    public var takenAt: Date?
    public var updatedAt: Date

    public enum CodingKeys: String, CodingKey {
        case userId = "user_id"
        case date
        case itemKey = "item_key"
        case taken
        case takenAt = "taken_at"
        case updatedAt = "updated_at"
    }

    public init(
        userId: String,
        date: String,
        itemKey: String,
        taken: Bool,
        takenAt: Date? = nil,
        updatedAt: Date
    ) {
        self.userId = userId
        self.date = date
        self.itemKey = itemKey
        self.taken = taken
        self.takenAt = takenAt
        self.updatedAt = updatedAt
    }
}

// MARK: - custom_supplements

/// Mirrors `public.custom_supplements` (daily). Pulled whole.
public struct CustomSupplementRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "custom_supplements"

    public var id: String
    public var userId: String
    public var name: String
    public var dose: String
    public var color: String?
    public var form: String?
    public var time: String?
    public var schedule: JSONText?
    public var micros: JSONText?
    public var createdAt: Date?
    public var archivedAt: Date?
    public var doseAmount: Double?
    public var doseUnit: String?
    public var sortOrder: Int?
    public var dosePeriods: JSONText?

    public enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case name
        case dose
        case color
        case form
        case time
        case schedule
        case micros
        case createdAt = "created_at"
        case archivedAt = "archived_at"
        case doseAmount = "dose_amount"
        case doseUnit = "dose_unit"
        case sortOrder = "sort_order"
        case dosePeriods = "dose_periods"
    }

    public init(
        id: String,
        userId: String,
        name: String,
        dose: String,
        color: String? = nil,
        form: String? = nil,
        time: String? = nil,
        schedule: JSONText? = nil,
        micros: JSONText? = nil,
        createdAt: Date? = nil,
        archivedAt: Date? = nil,
        doseAmount: Double? = nil,
        doseUnit: String? = nil,
        sortOrder: Int? = nil,
        dosePeriods: JSONText? = nil
    ) {
        self.id = id
        self.userId = userId
        self.name = name
        self.dose = dose
        self.color = color
        self.form = form
        self.time = time
        self.schedule = schedule
        self.micros = micros
        self.createdAt = createdAt
        self.archivedAt = archivedAt
        self.doseAmount = doseAmount
        self.doseUnit = doseUnit
        self.sortOrder = sortOrder
        self.dosePeriods = dosePeriods
    }
}

// MARK: - fatigue_logs

/// Mirrors `public.fatigue_logs` (daily). Windowed on `date`.
public struct FatigueLogRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "fatigue_logs"

    public var id: String
    public var userId: String
    public var date: String
    public var slot: String
    public var level: Int
    public var note: String?
    public var createdAt: Date?

    public enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case date
        case slot
        case level
        case note
        case createdAt = "created_at"
    }

    public init(
        id: String,
        userId: String,
        date: String,
        slot: String,
        level: Int,
        note: String? = nil,
        createdAt: Date? = nil
    ) {
        self.id = id
        self.userId = userId
        self.date = date
        self.slot = slot
        self.level = level
        self.note = note
        self.createdAt = createdAt
    }
}

// MARK: - stress_logs

/// Mirrors `public.stress_logs` (daily). Windowed on `date`.
public struct StressLogRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "stress_logs"

    public var id: String
    public var userId: String
    public var date: String
    public var slot: String
    public var level: Int
    public var tags: JSONText
    public var note: String?
    public var createdAt: Date
    public var updatedAt: Date
    public var loggedAt: Date?

    public enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case date
        case slot
        case level
        case tags
        case note
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case loggedAt = "logged_at"
    }

    public init(
        id: String,
        userId: String,
        date: String,
        slot: String,
        level: Int,
        tags: JSONText,
        note: String? = nil,
        createdAt: Date,
        updatedAt: Date,
        loggedAt: Date? = nil
    ) {
        self.id = id
        self.userId = userId
        self.date = date
        self.slot = slot
        self.level = level
        self.tags = tags
        self.note = note
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.loggedAt = loggedAt
    }
}

// MARK: - doms_logs

/// Mirrors `public.doms_logs` (daily). Windowed on `date`.
public struct DomsLogRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "doms_logs"

    public var id: String
    public var userId: String
    public var date: String
    public var muscleGroup: String
    public var severity: Int
    public var createdAt: Date?
    public var sourceSessionId: String?
    public var sourceDayKey: String?
    public var side: String?
    public var subRegion: String?

    public enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case date
        case muscleGroup = "muscle_group"
        case severity
        case createdAt = "created_at"
        case sourceSessionId = "source_session_id"
        case sourceDayKey = "source_day_key"
        case side
        case subRegion = "sub_region"
    }

    public init(
        id: String,
        userId: String,
        date: String,
        muscleGroup: String,
        severity: Int,
        createdAt: Date? = nil,
        sourceSessionId: String? = nil,
        sourceDayKey: String? = nil,
        side: String? = nil,
        subRegion: String? = nil
    ) {
        self.id = id
        self.userId = userId
        self.date = date
        self.muscleGroup = muscleGroup
        self.severity = severity
        self.createdAt = createdAt
        self.sourceSessionId = sourceSessionId
        self.sourceDayKey = sourceDayKey
        self.side = side
        self.subRegion = subRegion
    }
}

// MARK: - body_composition

/// Mirrors `public.body_composition` (body). Windowed on `date`.
public struct BodyCompositionRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "body_composition"

    public var id: String
    public var userId: String
    public var hkUuid: String?
    public var measuredAt: Date
    public var date: String
    public var weightKg: Double
    public var bodyFatPct: Double?
    public var muscleMassKg: Double?
    public var waterPct: Double?
    public var boneMassKg: Double?
    public var bmi: Double?
    public var createdAt: Date
    public var fatMassKg: Double?
    public var bodyWaterMassKg: Double?
    public var proteinMassKg: Double?
    public var musclePct: Double?
    public var proteinPct: Double?
    public var boneMineralPct: Double?
    public var skeletalMuscleMassKg: Double?
    public var fatFreeMassKg: Double?
    public var visceralFat: Double?
    public var bmr: Double?
    public var estimatedWaistToHipRatio: Double?

    public enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case hkUuid = "hk_uuid"
        case measuredAt = "measured_at"
        case date
        case weightKg = "weight_kg"
        case bodyFatPct = "body_fat_pct"
        case muscleMassKg = "muscle_mass_kg"
        case waterPct = "water_pct"
        case boneMassKg = "bone_mass_kg"
        case bmi
        case createdAt = "created_at"
        case fatMassKg = "fat_mass_kg"
        case bodyWaterMassKg = "body_water_mass_kg"
        case proteinMassKg = "protein_mass_kg"
        case musclePct = "muscle_pct"
        case proteinPct = "protein_pct"
        case boneMineralPct = "bone_mineral_pct"
        case skeletalMuscleMassKg = "skeletal_muscle_mass_kg"
        case fatFreeMassKg = "fat_free_mass_kg"
        case visceralFat = "visceral_fat"
        case bmr
        case estimatedWaistToHipRatio = "estimated_waist_to_hip_ratio"
    }

    public init(
        id: String,
        userId: String,
        hkUuid: String? = nil,
        measuredAt: Date,
        date: String,
        weightKg: Double,
        bodyFatPct: Double? = nil,
        muscleMassKg: Double? = nil,
        waterPct: Double? = nil,
        boneMassKg: Double? = nil,
        bmi: Double? = nil,
        createdAt: Date,
        fatMassKg: Double? = nil,
        bodyWaterMassKg: Double? = nil,
        proteinMassKg: Double? = nil,
        musclePct: Double? = nil,
        proteinPct: Double? = nil,
        boneMineralPct: Double? = nil,
        skeletalMuscleMassKg: Double? = nil,
        fatFreeMassKg: Double? = nil,
        visceralFat: Double? = nil,
        bmr: Double? = nil,
        estimatedWaistToHipRatio: Double? = nil
    ) {
        self.id = id
        self.userId = userId
        self.hkUuid = hkUuid
        self.measuredAt = measuredAt
        self.date = date
        self.weightKg = weightKg
        self.bodyFatPct = bodyFatPct
        self.muscleMassKg = muscleMassKg
        self.waterPct = waterPct
        self.boneMassKg = boneMassKg
        self.bmi = bmi
        self.createdAt = createdAt
        self.fatMassKg = fatMassKg
        self.bodyWaterMassKg = bodyWaterMassKg
        self.proteinMassKg = proteinMassKg
        self.musclePct = musclePct
        self.proteinPct = proteinPct
        self.boneMineralPct = boneMineralPct
        self.skeletalMuscleMassKg = skeletalMuscleMassKg
        self.fatFreeMassKg = fatFreeMassKg
        self.visceralFat = visceralFat
        self.bmr = bmr
        self.estimatedWaistToHipRatio = estimatedWaistToHipRatio
    }
}

// MARK: - sleep_sessions

/// Mirrors `public.sleep_sessions` (body). Windowed on `start_time`.
public struct SleepSessionRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "sleep_sessions"

    public var id: String
    public var userId: String
    public var hkUuid: String?
    public var startTime: Date
    public var endTime: Date
    public var durationMin: Int
    public var deepMin: Int?
    public var remMin: Int?
    public var coreMin: Int?
    public var awakeMin: Int?
    public var sleepScore: Int?
    public var createdAt: Date
    public var onsetTime: Date?
    public var awakenings: Int?

    public enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case hkUuid = "hk_uuid"
        case startTime = "start_time"
        case endTime = "end_time"
        case durationMin = "duration_min"
        case deepMin = "deep_min"
        case remMin = "rem_min"
        case coreMin = "core_min"
        case awakeMin = "awake_min"
        case sleepScore = "sleep_score"
        case createdAt = "created_at"
        case onsetTime = "onset_time"
        case awakenings
    }

    public init(
        id: String,
        userId: String,
        hkUuid: String? = nil,
        startTime: Date,
        endTime: Date,
        durationMin: Int,
        deepMin: Int? = nil,
        remMin: Int? = nil,
        coreMin: Int? = nil,
        awakeMin: Int? = nil,
        sleepScore: Int? = nil,
        createdAt: Date,
        onsetTime: Date? = nil,
        awakenings: Int? = nil
    ) {
        self.id = id
        self.userId = userId
        self.hkUuid = hkUuid
        self.startTime = startTime
        self.endTime = endTime
        self.durationMin = durationMin
        self.deepMin = deepMin
        self.remMin = remMin
        self.coreMin = coreMin
        self.awakeMin = awakeMin
        self.sleepScore = sleepScore
        self.createdAt = createdAt
        self.onsetTime = onsetTime
        self.awakenings = awakenings
    }
}

// MARK: - cardio_logs

/// Mirrors `public.cardio_logs` (body). Windowed on `date`.
public struct CardioLogRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "cardio_logs"

    public var id: String
    public var userId: String
    public var date: String
    public var kind: String
    public var distanceM: Double?
    public var durationMin: Double?
    public var kcal: Double?
    public var fromHealthkit: Bool?
    public var createdAt: Date?
    public var activeKcal: Double?
    public var totalKcal: Double?
    public var avgHr: Double?
    public var effort: Double?
    public var sessionId: String?
    public var inclinePct: Double?
    public var elevationM: Double?
    public var hkUuid: String?

    public enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case date
        case kind
        case distanceM = "distance_m"
        case durationMin = "duration_min"
        case kcal
        case fromHealthkit = "from_healthkit"
        case createdAt = "created_at"
        case activeKcal = "active_kcal"
        case totalKcal = "total_kcal"
        case avgHr = "avg_hr"
        case effort
        case sessionId = "session_id"
        case inclinePct = "incline_pct"
        case elevationM = "elevation_m"
        case hkUuid = "hk_uuid"
    }

    public init(
        id: String,
        userId: String,
        date: String,
        kind: String,
        distanceM: Double? = nil,
        durationMin: Double? = nil,
        kcal: Double? = nil,
        fromHealthkit: Bool? = nil,
        createdAt: Date? = nil,
        activeKcal: Double? = nil,
        totalKcal: Double? = nil,
        avgHr: Double? = nil,
        effort: Double? = nil,
        sessionId: String? = nil,
        inclinePct: Double? = nil,
        elevationM: Double? = nil,
        hkUuid: String? = nil
    ) {
        self.id = id
        self.userId = userId
        self.date = date
        self.kind = kind
        self.distanceM = distanceM
        self.durationMin = durationMin
        self.kcal = kcal
        self.fromHealthkit = fromHealthkit
        self.createdAt = createdAt
        self.activeKcal = activeKcal
        self.totalKcal = totalKcal
        self.avgHr = avgHr
        self.effort = effort
        self.sessionId = sessionId
        self.inclinePct = inclinePct
        self.elevationM = elevationM
        self.hkUuid = hkUuid
    }
}

// MARK: - personal_records

/// Mirrors `public.personal_records` (training). Delta by `updated_at`.
public struct PersonalRecordRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "personal_records"

    public var userId: String
    public var exerciseKey: String
    public var axis: String
    public var value: Double
    public var reps: Int?
    public var weightKg: Double?
    public var sessionId: String?
    public var achievedOn: String
    public var updatedAt: Date?
    public var floorValue: Double?

    public enum CodingKeys: String, CodingKey {
        case userId = "user_id"
        case exerciseKey = "exercise_key"
        case axis
        case value
        case reps
        case weightKg = "weight_kg"
        case sessionId = "session_id"
        case achievedOn = "achieved_on"
        case updatedAt = "updated_at"
        case floorValue = "floor_value"
    }

    public init(
        userId: String,
        exerciseKey: String,
        axis: String,
        value: Double,
        reps: Int? = nil,
        weightKg: Double? = nil,
        sessionId: String? = nil,
        achievedOn: String,
        updatedAt: Date? = nil,
        floorValue: Double? = nil
    ) {
        self.userId = userId
        self.exerciseKey = exerciseKey
        self.axis = axis
        self.value = value
        self.reps = reps
        self.weightKg = weightKg
        self.sessionId = sessionId
        self.achievedOn = achievedOn
        self.updatedAt = updatedAt
        self.floorValue = floorValue
    }
}

// MARK: - routine_templates

/// Mirrors `public.routine_templates` (training). Delta by `updated_at`.
public struct RoutineTemplateRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "routine_templates"

    public var userId: String
    public var dayKey: String
    public var payload: JSONText
    public var sourceSessionId: String?
    public var updatedAt: Date

    public enum CodingKeys: String, CodingKey {
        case userId = "user_id"
        case dayKey = "day_key"
        case payload
        case sourceSessionId = "source_session_id"
        case updatedAt = "updated_at"
    }

    public init(
        userId: String,
        dayKey: String,
        payload: JSONText,
        sourceSessionId: String? = nil,
        updatedAt: Date
    ) {
        self.userId = userId
        self.dayKey = dayKey
        self.payload = payload
        self.sourceSessionId = sourceSessionId
        self.updatedAt = updatedAt
    }
}

// MARK: - routines

/// Mirrors `public.routines` (training). Delta by `updated_at`.
public struct RoutineRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "routines"

    public var userId: String
    public var programId: String
    public var dayKey: String
    public var label: String
    public var sub: String?
    public var weekday: Int
    public var accent: Int
    public var sort: Int
    public var payload: JSONText
    public var updatedAt: Date

    public enum CodingKeys: String, CodingKey {
        case userId = "user_id"
        case programId = "program_id"
        case dayKey = "day_key"
        case label
        case sub
        case weekday
        case accent
        case sort
        case payload
        case updatedAt = "updated_at"
    }

    public init(
        userId: String,
        programId: String,
        dayKey: String,
        label: String,
        sub: String? = nil,
        weekday: Int,
        accent: Int,
        sort: Int,
        payload: JSONText,
        updatedAt: Date
    ) {
        self.userId = userId
        self.programId = programId
        self.dayKey = dayKey
        self.label = label
        self.sub = sub
        self.weekday = weekday
        self.accent = accent
        self.sort = sort
        self.payload = payload
        self.updatedAt = updatedAt
    }
}

// MARK: - user_goals

/// Mirrors `public.user_goals` (plan). Delta by `updated_at`.
public struct UserGoalRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "user_goals"

    public var id: String
    public var userId: String
    public var sleepGoalHours: Double?
    public var calorieGoal: Int?
    public var proteinGoalG: Int?
    public var carbsGoalG: Int?
    public var fatGoalG: Int?
    public var stepsGoal: Int?
    public var activeCalGoal: Int?
    public var waterGoalMl: Int?
    public var contextMode: String
    public var goalPreset: String?
    public var createdAt: Date
    public var updatedAt: Date
    public var autoLogSupplements: Bool
    public var activeProgram: String
    public var dayCutoffHour: Int
    public var unitSystem: String
    public var reduceMotion: Bool
    public var timezone: String
    public var targetWeightKg: Double?
    public var weekEndDay: Int?
    public var activePlan: String?
    public var targetBodyFatPct: Double?
    public var targetMuscleMassKg: Double?
    public var activePhase: String?
    public var phaseStartedOn: String?
    public var trackRpe: Bool
    public var activeLever: String?
    public var contextSince: String?
    public var maintenanceUntil: String?

    public enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case sleepGoalHours = "sleep_goal_hours"
        case calorieGoal = "calorie_goal"
        case proteinGoalG = "protein_goal_g"
        case carbsGoalG = "carbs_goal_g"
        case fatGoalG = "fat_goal_g"
        case stepsGoal = "steps_goal"
        case activeCalGoal = "active_cal_goal"
        case waterGoalMl = "water_goal_ml"
        case contextMode = "context_mode"
        case goalPreset = "goal_preset"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case autoLogSupplements = "auto_log_supplements"
        case activeProgram = "active_program"
        case dayCutoffHour = "day_cutoff_hour"
        case unitSystem = "unit_system"
        case reduceMotion = "reduce_motion"
        case timezone
        case targetWeightKg = "target_weight_kg"
        case weekEndDay = "week_end_day"
        case activePlan = "active_plan"
        case targetBodyFatPct = "target_body_fat_pct"
        case targetMuscleMassKg = "target_muscle_mass_kg"
        case activePhase = "active_phase"
        case phaseStartedOn = "phase_started_on"
        case trackRpe = "track_rpe"
        case activeLever = "active_lever"
        case contextSince = "context_since"
        case maintenanceUntil = "maintenance_until"
    }

    public init(
        id: String,
        userId: String,
        sleepGoalHours: Double? = nil,
        calorieGoal: Int? = nil,
        proteinGoalG: Int? = nil,
        carbsGoalG: Int? = nil,
        fatGoalG: Int? = nil,
        stepsGoal: Int? = nil,
        activeCalGoal: Int? = nil,
        waterGoalMl: Int? = nil,
        contextMode: String,
        goalPreset: String? = nil,
        createdAt: Date,
        updatedAt: Date,
        autoLogSupplements: Bool,
        activeProgram: String,
        dayCutoffHour: Int,
        unitSystem: String,
        reduceMotion: Bool,
        timezone: String,
        targetWeightKg: Double? = nil,
        weekEndDay: Int? = nil,
        activePlan: String? = nil,
        targetBodyFatPct: Double? = nil,
        targetMuscleMassKg: Double? = nil,
        activePhase: String? = nil,
        phaseStartedOn: String? = nil,
        trackRpe: Bool,
        activeLever: String? = nil,
        contextSince: String? = nil,
        maintenanceUntil: String? = nil
    ) {
        self.id = id
        self.userId = userId
        self.sleepGoalHours = sleepGoalHours
        self.calorieGoal = calorieGoal
        self.proteinGoalG = proteinGoalG
        self.carbsGoalG = carbsGoalG
        self.fatGoalG = fatGoalG
        self.stepsGoal = stepsGoal
        self.activeCalGoal = activeCalGoal
        self.waterGoalMl = waterGoalMl
        self.contextMode = contextMode
        self.goalPreset = goalPreset
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.autoLogSupplements = autoLogSupplements
        self.activeProgram = activeProgram
        self.dayCutoffHour = dayCutoffHour
        self.unitSystem = unitSystem
        self.reduceMotion = reduceMotion
        self.timezone = timezone
        self.targetWeightKg = targetWeightKg
        self.weekEndDay = weekEndDay
        self.activePlan = activePlan
        self.targetBodyFatPct = targetBodyFatPct
        self.targetMuscleMassKg = targetMuscleMassKg
        self.activePhase = activePhase
        self.phaseStartedOn = phaseStartedOn
        self.trackRpe = trackRpe
        self.activeLever = activeLever
        self.contextSince = contextSince
        self.maintenanceUntil = maintenanceUntil
    }
}

// MARK: - target_profiles

/// Mirrors `public.target_profiles` (plan). Delta by `updated_at`.
public struct TargetProfileRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "target_profiles"

    public var userId: String
    public var key: String
    public var label: String
    public var summary: String?
    public var sort: Int
    public var kcal: Int?
    public var proteinG: Int?
    public var carbsG: Int?
    public var fatG: Int?
    public var stepsGoal: Int?
    public var updatedAt: Date
    public var kind: String?

    public enum CodingKeys: String, CodingKey {
        case userId = "user_id"
        case key
        case label
        case summary
        case sort
        case kcal
        case proteinG = "protein_g"
        case carbsG = "carbs_g"
        case fatG = "fat_g"
        case stepsGoal = "steps_goal"
        case updatedAt = "updated_at"
        case kind
    }

    public init(
        userId: String,
        key: String,
        label: String,
        summary: String? = nil,
        sort: Int,
        kcal: Int? = nil,
        proteinG: Int? = nil,
        carbsG: Int? = nil,
        fatG: Int? = nil,
        stepsGoal: Int? = nil,
        updatedAt: Date,
        kind: String? = nil
    ) {
        self.userId = userId
        self.key = key
        self.label = label
        self.summary = summary
        self.sort = sort
        self.kcal = kcal
        self.proteinG = proteinG
        self.carbsG = carbsG
        self.fatG = fatG
        self.stepsGoal = stepsGoal
        self.updatedAt = updatedAt
        self.kind = kind
    }
}

// MARK: - plans

/// Mirrors `public.plans` (plan). Pulled whole.
public struct PlanRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "plans"

    public var id: String
    public var userId: String
    public var name: String
    public var programId: String?
    public var active: Bool?
    public var startedOn: String?
    public var createdAt: Date?
    public var blurb: String?
    public var isLegacy: Bool?
    public var sort: Int?

    public enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case name
        case programId = "program_id"
        case active
        case startedOn = "started_on"
        case createdAt = "created_at"
        case blurb
        case isLegacy = "is_legacy"
        case sort
    }

    public init(
        id: String,
        userId: String,
        name: String,
        programId: String? = nil,
        active: Bool? = nil,
        startedOn: String? = nil,
        createdAt: Date? = nil,
        blurb: String? = nil,
        isLegacy: Bool? = nil,
        sort: Int? = nil
    ) {
        self.id = id
        self.userId = userId
        self.name = name
        self.programId = programId
        self.active = active
        self.startedOn = startedOn
        self.createdAt = createdAt
        self.blurb = blurb
        self.isLegacy = isLegacy
        self.sort = sort
    }
}

// MARK: - plan_phase_goals

/// Mirrors `public.plan_phase_goals` (plan). Delta by `updated_at`.
public struct PlanPhaseGoalRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "plan_phase_goals"

    public var userId: String
    public var planId: String
    public var phase: String
    public var kcal: Int?
    public var proteinG: Int?
    public var carbsG: Int?
    public var fatG: Int?
    public var fiberMin: Int?
    public var fiberMax: Int?
    public var updatedAt: Date?
    public var stepsGoal: Int?
    public var targetWeightKg: Double?
    public var targetBodyFatPct: Double?
    public var targetMuscleMassKg: Double?
    public var rateMinKgWk: Double?
    public var rateMaxKgWk: Double?
    public var label: String?
    public var fiberG: Int?
    public var bodyFatCeilingPct: Double?

    public enum CodingKeys: String, CodingKey {
        case userId = "user_id"
        case planId = "plan_id"
        case phase
        case kcal
        case proteinG = "protein_g"
        case carbsG = "carbs_g"
        case fatG = "fat_g"
        case fiberMin = "fiber_min"
        case fiberMax = "fiber_max"
        case updatedAt = "updated_at"
        case stepsGoal = "steps_goal"
        case targetWeightKg = "target_weight_kg"
        case targetBodyFatPct = "target_body_fat_pct"
        case targetMuscleMassKg = "target_muscle_mass_kg"
        case rateMinKgWk = "rate_min_kg_wk"
        case rateMaxKgWk = "rate_max_kg_wk"
        case label
        case fiberG = "fiber_g"
        case bodyFatCeilingPct = "body_fat_ceiling_pct"
    }

    public init(
        userId: String,
        planId: String,
        phase: String,
        kcal: Int? = nil,
        proteinG: Int? = nil,
        carbsG: Int? = nil,
        fatG: Int? = nil,
        fiberMin: Int? = nil,
        fiberMax: Int? = nil,
        updatedAt: Date? = nil,
        stepsGoal: Int? = nil,
        targetWeightKg: Double? = nil,
        targetBodyFatPct: Double? = nil,
        targetMuscleMassKg: Double? = nil,
        rateMinKgWk: Double? = nil,
        rateMaxKgWk: Double? = nil,
        label: String? = nil,
        fiberG: Int? = nil,
        bodyFatCeilingPct: Double? = nil
    ) {
        self.userId = userId
        self.planId = planId
        self.phase = phase
        self.kcal = kcal
        self.proteinG = proteinG
        self.carbsG = carbsG
        self.fatG = fatG
        self.fiberMin = fiberMin
        self.fiberMax = fiberMax
        self.updatedAt = updatedAt
        self.stepsGoal = stepsGoal
        self.targetWeightKg = targetWeightKg
        self.targetBodyFatPct = targetBodyFatPct
        self.targetMuscleMassKg = targetMuscleMassKg
        self.rateMinKgWk = rateMinKgWk
        self.rateMaxKgWk = rateMaxKgWk
        self.label = label
        self.fiberG = fiberG
        self.bodyFatCeilingPct = bodyFatCeilingPct
    }
}

// MARK: - plan_phase_volume

/// Mirrors `public.plan_phase_volume` (plan). Delta by `updated_at`.
public struct PlanPhaseVolumeRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "plan_phase_volume"

    public var userId: String
    public var planId: String
    public var phase: String
    public var muscle: String
    public var targetSets: Int
    public var updatedAt: Date?

    public enum CodingKeys: String, CodingKey {
        case userId = "user_id"
        case planId = "plan_id"
        case phase
        case muscle
        case targetSets = "target_sets"
        case updatedAt = "updated_at"
    }

    public init(
        userId: String,
        planId: String,
        phase: String,
        muscle: String,
        targetSets: Int,
        updatedAt: Date? = nil
    ) {
        self.userId = userId
        self.planId = planId
        self.phase = phase
        self.muscle = muscle
        self.targetSets = targetSets
        self.updatedAt = updatedAt
    }
}

// MARK: - program_day_layout

/// Mirrors `public.program_day_layout` (plan). Delta by `updated_at`.
public struct ProgramDayLayoutRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "program_day_layout"

    public var userId: String
    public var programId: String
    public var layout: JSONText
    public var updatedAt: Date

    public enum CodingKeys: String, CodingKey {
        case userId = "user_id"
        case programId = "program_id"
        case layout
        case updatedAt = "updated_at"
    }

    public init(
        userId: String,
        programId: String,
        layout: JSONText,
        updatedAt: Date
    ) {
        self.userId = userId
        self.programId = programId
        self.layout = layout
        self.updatedAt = updatedAt
    }
}

// MARK: - plan_phases

/// Mirrors `public.plan_phases` (plan). Pulled whole.
public struct PlanPhaseRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "plan_phases"

    public var userId: String
    public var planId: String
    public var start: String
    public var kind: String
    public var name: String
    public var short: String?
    public var weeks: Int
    public var numbered: Bool
    public var firstWeek: Int?
    public var era: String?
    public var eraTag: String?
    public var updatedAt: Date

    public enum CodingKeys: String, CodingKey {
        case userId = "user_id"
        case planId = "plan_id"
        case start
        case kind
        case name
        case short
        case weeks
        case numbered
        case firstWeek = "first_week"
        case era
        case eraTag = "era_tag"
        case updatedAt = "updated_at"
    }

    public init(
        userId: String,
        planId: String,
        start: String,
        kind: String,
        name: String,
        short: String? = nil,
        weeks: Int,
        numbered: Bool,
        firstWeek: Int? = nil,
        era: String? = nil,
        eraTag: String? = nil,
        updatedAt: Date
    ) {
        self.userId = userId
        self.planId = planId
        self.start = start
        self.kind = kind
        self.name = name
        self.short = short
        self.weeks = weeks
        self.numbered = numbered
        self.firstWeek = firstWeek
        self.era = era
        self.eraTag = eraTag
        self.updatedAt = updatedAt
    }
}

// MARK: - lever_periods

/// Mirrors `public.lever_periods` (plan). Pulled whole.
public struct LeverPeriodRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "lever_periods"

    public var userId: String
    public var startsOn: String
    public var profileKey: String?
    public var goals: JSONText?
    public var updatedAt: Date

    public enum CodingKeys: String, CodingKey {
        case userId = "user_id"
        case startsOn = "starts_on"
        case profileKey = "profile_key"
        case goals
        case updatedAt = "updated_at"
    }

    public init(
        userId: String,
        startsOn: String,
        profileKey: String? = nil,
        goals: JSONText? = nil,
        updatedAt: Date
    ) {
        self.userId = userId
        self.startsOn = startsOn
        self.profileKey = profileKey
        self.goals = goals
        self.updatedAt = updatedAt
    }
}

// MARK: - schedule_overrides

/// Mirrors `public.schedule_overrides` (plan). Delta by `updated_at`.
public struct ScheduleOverrideRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "schedule_overrides"

    public var userId: String
    public var date: String
    public var dayKey: String
    public var updatedAt: Date

    public enum CodingKeys: String, CodingKey {
        case userId = "user_id"
        case date
        case dayKey = "day_key"
        case updatedAt = "updated_at"
    }

    public init(
        userId: String,
        date: String,
        dayKey: String,
        updatedAt: Date
    ) {
        self.userId = userId
        self.date = date
        self.dayKey = dayKey
        self.updatedAt = updatedAt
    }
}

// MARK: - dashboard_layouts

/// Mirrors `public.dashboard_layouts` (plan). Delta by `updated_at`.
public struct DashboardLayoutRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "dashboard_layouts"

    public var userId: String
    public var layout: JSONText
    public var updatedAt: Date

    public enum CodingKeys: String, CodingKey {
        case userId = "user_id"
        case layout
        case updatedAt = "updated_at"
    }

    public init(
        userId: String,
        layout: JSONText,
        updatedAt: Date
    ) {
        self.userId = userId
        self.layout = layout
        self.updatedAt = updatedAt
    }
}

// MARK: - profiles

/// Mirrors `public.profiles` (plan). Delta by `updated_at`.
public struct ProfileRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "profiles"

    public var userId: String
    public var displayName: String?
    public var role: String
    public var updatedAt: Date
    public var createdAt: Date

    public enum CodingKeys: String, CodingKey {
        case userId = "user_id"
        case displayName = "display_name"
        case role
        case updatedAt = "updated_at"
        case createdAt = "created_at"
    }

    public init(
        userId: String,
        displayName: String? = nil,
        role: String,
        updatedAt: Date,
        createdAt: Date
    ) {
        self.userId = userId
        self.displayName = displayName
        self.role = role
        self.updatedAt = updatedAt
        self.createdAt = createdAt
    }
}

// MARK: - reports

/// Mirrors `public.reports` (reports). Pulled whole.
public struct ReportRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "reports"

    public var id: String
    public var userId: String
    public var type: String
    public var periodStart: String
    public var periodEnd: String
    public var contentMd: String?
    public var sessionSummaryMd: String?
    public var weightReportMd: String?
    public var metrics: JSONText?
    public var notionPageId: String?
    public var createdAt: Date

    public enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case type
        case periodStart = "period_start"
        case periodEnd = "period_end"
        case contentMd = "content_md"
        case sessionSummaryMd = "session_summary_md"
        case weightReportMd = "weight_report_md"
        case metrics
        case notionPageId = "notion_page_id"
        case createdAt = "created_at"
    }

    public init(
        id: String,
        userId: String,
        type: String,
        periodStart: String,
        periodEnd: String,
        contentMd: String? = nil,
        sessionSummaryMd: String? = nil,
        weightReportMd: String? = nil,
        metrics: JSONText? = nil,
        notionPageId: String? = nil,
        createdAt: Date
    ) {
        self.id = id
        self.userId = userId
        self.type = type
        self.periodStart = periodStart
        self.periodEnd = periodEnd
        self.contentMd = contentMd
        self.sessionSummaryMd = sessionSummaryMd
        self.weightReportMd = weightReportMd
        self.metrics = metrics
        self.notionPageId = notionPageId
        self.createdAt = createdAt
    }
}

// MARK: - prescriptions

/// Mirrors `public.prescriptions` (training). Pulled whole.
public struct PrescriptionRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "prescriptions"

    public var id: String
    public var userId: String
    public var exerciseKey: String
    public var version: Int
    public var effectiveFrom: String
    public var loadKg: Double?
    public var sets: Int?
    public var repRange: String?
    public var rpeCap: Double?
    public var structure: String
    public var setLoads: JSONText?
    public var leadRule: String
    public var notes: String?
    public var createdAt: Date

    public enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case exerciseKey = "exercise_key"
        case version
        case effectiveFrom = "effective_from"
        case loadKg = "load_kg"
        case sets
        case repRange = "rep_range"
        case rpeCap = "rpe_cap"
        case structure
        case setLoads = "set_loads"
        case leadRule = "lead_rule"
        case notes
        case createdAt = "created_at"
    }

    public init(
        id: String,
        userId: String,
        exerciseKey: String,
        version: Int,
        effectiveFrom: String,
        loadKg: Double? = nil,
        sets: Int? = nil,
        repRange: String? = nil,
        rpeCap: Double? = nil,
        structure: String,
        setLoads: JSONText? = nil,
        leadRule: String,
        notes: String? = nil,
        createdAt: Date
    ) {
        self.id = id
        self.userId = userId
        self.exerciseKey = exerciseKey
        self.version = version
        self.effectiveFrom = effectiveFrom
        self.loadKg = loadKg
        self.sets = sets
        self.repRange = repRange
        self.rpeCap = rpeCap
        self.structure = structure
        self.setLoads = setLoads
        self.leadRule = leadRule
        self.notes = notes
        self.createdAt = createdAt
    }
}

// MARK: - Schema

extension AppDatabase {
    /// The mirror's tables, as one migration.
    ///
    /// Registered by `AppDatabase.migrator`. Append-only like every other
    /// migration here: a regenerated schema is a NEW migration, never an edit
    /// to this one, because an edited migration runs on a fresh install and
    /// not on yours.
    static func migrateMirrorV1(_ db: Database) throws {
            try db.create(table: "daily_logs") { t in
                t.primaryKey("id", .text)
                t.column("user_id", .text).notNull()
                t.column("date", .text).notNull()
                t.column("steps", .integer)
                t.column("water_ml", .double)
                t.column("sleep_minutes", .integer)
                t.column("carbs_g", .double)
                t.column("protein_g", .double)
                t.column("fats_g", .double)
                t.column("weight_kg", .double)
                t.column("lean_mass_kg", .double)
                t.column("bmi", .double)
                t.column("training_minutes", .integer)
                t.column("active_energy", .double)
                t.column("body_fat_pct", .double)
                t.column("standing_minutes", .integer)
                t.column("avg_heart_rate", .integer)
                t.column("avg_rest_heart_rate", .integer)
                t.column("respiratory_rate", .double)
                t.column("blood_oxygen", .double)
                t.column("muscle_percent", .double)
                t.column("water_percent", .double)
                t.column("bone_mineral", .double)
                t.column("visceral_fat", .double)
                t.column("bmr", .double)
                t.column("created_at", .datetime).notNull()
                t.column("updated_at", .datetime).notNull()
                t.column("hrv_ms", .double)
                t.column("exercise_minutes", .integer)
                t.column("stand_hours", .integer)
                t.column("vo2max", .double)
                t.column("wrist_temp_delta", .double)
                t.column("time_in_daylight_min", .integer)
                t.column("effort_rating", .integer)
                t.column("mood", .integer)
                t.column("journal_md", .text)
                t.column("distance_m", .double)
                t.column("protein_percent", .double)
                t.column("muscle_mass_kg", .double)
                t.column("water_mass_kg", .double)
                t.column("fat_mass_kg", .double)
                t.column("bone_mineral_kg", .double)
                t.column("protein_mass_kg", .double)
                t.column("fat_free_mass_kg", .double)
                t.column("weighin_skip_reason", .text)
                t.column("skeletal_muscle_mass_kg", .double)
                t.column("estimated_waist_to_hip_ratio", .double)
                t.column("waist_cm", .double)
                t.column("nutrition_exception", .text)
                t.column("nutrition_estimated", .boolean).notNull()
                t.column("sleep_onset_trouble", .boolean).notNull()
                t.column("sleep_inaccurate", .boolean)
                t.column("hrv_overnight", .boolean)
            }
            try db.create(table: "daily_metrics") { t in
                t.primaryKey("id", .text)
                t.column("user_id", .text).notNull()
                t.column("date", .text).notNull()
                t.column("steps", .integer)
                t.column("active_cal", .integer)
                t.column("rest_hr", .integer)
                t.column("created_at", .datetime).notNull()
                t.column("updated_at", .datetime).notNull()
            }
            try db.create(table: "daily_scores") { t in
                t.primaryKey("id", .text)
                t.column("user_id", .text).notNull()
                t.column("date", .text).notNull()
                t.column("score", .integer).notNull()
                t.column("sleep_score", .integer)
                t.column("nutrition_score", .integer)
                t.column("activity_score", .integer)
                t.column("workout_score", .integer)
                t.column("recovery_score", .integer)
                t.column("battery_pct", .integer)
                t.column("computed_at", .datetime).notNull()
                t.column("finalized", .boolean).notNull()
            }
            try db.create(table: "daily_targets") { t in
                t.column("user_id", .text).notNull()
                t.column("date", .text).notNull()
                t.column("kcal", .integer)
                t.column("protein_g", .integer)
                t.column("carbs_g", .integer)
                t.column("fat_g", .integer)
                t.column("steps_goal", .integer)
                t.column("note", .text)
                t.column("updated_at", .datetime).notNull()
                t.column("profile_key", .text)
                t.column("track_carbs", .boolean).notNull()
                t.column("track_fat", .boolean).notNull()
                t.primaryKey(["user_id", "date"])
            }
            try db.create(table: "nutrition_entries") { t in
                t.primaryKey("id", .text)
                t.column("user_id", .text).notNull()
                t.column("hk_uuid", .text)
                t.column("logged_at", .datetime).notNull()
                t.column("date", .text).notNull()
                t.column("meal_type", .text)
                t.column("calories", .double).notNull()
                t.column("protein_g", .double).notNull()
                t.column("carbs_g", .double).notNull()
                t.column("fat_g", .double).notNull()
                t.column("fiber_g", .double)
                t.column("phase", .text)
                t.column("created_at", .datetime).notNull()
                t.column("target_kcal", .integer)
                t.column("micros", .text)
            }
            try db.create(table: "water_intake") { t in
                t.primaryKey("id", .text)
                t.column("user_id", .text).notNull()
                t.column("hk_uuid", .text)
                t.column("logged_at", .datetime).notNull()
                t.column("date", .text).notNull()
                t.column("amount_ml", .double).notNull()
                t.column("created_at", .datetime).notNull()
            }
            try db.create(table: "supplement_log") { t in
                t.column("user_id", .text).notNull()
                t.column("date", .text).notNull()
                t.column("item_key", .text).notNull()
                t.column("taken", .boolean).notNull()
                t.column("taken_at", .datetime)
                t.column("updated_at", .datetime).notNull()
                t.primaryKey(["user_id", "date", "item_key"])
            }
            try db.create(table: "custom_supplements") { t in
                t.primaryKey("id", .text)
                t.column("user_id", .text).notNull()
                t.column("name", .text).notNull()
                t.column("dose", .text).notNull()
                t.column("color", .text)
                t.column("form", .text)
                t.column("time", .text)
                t.column("schedule", .text)
                t.column("micros", .text)
                t.column("created_at", .datetime)
                t.column("archived_at", .datetime)
                t.column("dose_amount", .double)
                t.column("dose_unit", .text)
                t.column("sort_order", .integer)
                t.column("dose_periods", .text)
            }
            try db.create(table: "fatigue_logs") { t in
                t.primaryKey("id", .text)
                t.column("user_id", .text).notNull()
                t.column("date", .text).notNull()
                t.column("slot", .text).notNull()
                t.column("level", .integer).notNull()
                t.column("note", .text)
                t.column("created_at", .datetime)
            }
            try db.create(table: "doms_logs") { t in
                t.primaryKey("id", .text)
                t.column("user_id", .text).notNull()
                t.column("date", .text).notNull()
                t.column("muscle_group", .text).notNull()
                t.column("severity", .integer).notNull()
                t.column("created_at", .datetime)
                t.column("source_session_id", .text)
                t.column("source_day_key", .text)
                t.column("side", .text)
                t.column("sub_region", .text)
            }
            try db.create(table: "body_composition") { t in
                t.primaryKey("id", .text)
                t.column("user_id", .text).notNull()
                t.column("hk_uuid", .text)
                t.column("measured_at", .datetime).notNull()
                t.column("date", .text).notNull()
                t.column("weight_kg", .double).notNull()
                t.column("body_fat_pct", .double)
                t.column("muscle_mass_kg", .double)
                t.column("water_pct", .double)
                t.column("bone_mass_kg", .double)
                t.column("bmi", .double)
                t.column("created_at", .datetime).notNull()
                t.column("fat_mass_kg", .double)
                t.column("body_water_mass_kg", .double)
                t.column("protein_mass_kg", .double)
                t.column("muscle_pct", .double)
                t.column("protein_pct", .double)
                t.column("bone_mineral_pct", .double)
                t.column("skeletal_muscle_mass_kg", .double)
                t.column("fat_free_mass_kg", .double)
                t.column("visceral_fat", .double)
                t.column("bmr", .double)
                t.column("estimated_waist_to_hip_ratio", .double)
            }
            try db.create(table: "sleep_sessions") { t in
                t.primaryKey("id", .text)
                t.column("user_id", .text).notNull()
                t.column("hk_uuid", .text)
                t.column("start_time", .datetime).notNull()
                t.column("end_time", .datetime).notNull()
                t.column("duration_min", .integer).notNull()
                t.column("deep_min", .integer)
                t.column("rem_min", .integer)
                t.column("core_min", .integer)
                t.column("awake_min", .integer)
                t.column("sleep_score", .integer)
                t.column("created_at", .datetime).notNull()
                t.column("onset_time", .datetime)
                t.column("awakenings", .integer)
            }
            try db.create(table: "cardio_logs") { t in
                t.primaryKey("id", .text)
                t.column("user_id", .text).notNull()
                t.column("date", .text).notNull()
                t.column("kind", .text).notNull()
                t.column("distance_m", .double)
                t.column("duration_min", .double)
                t.column("kcal", .double)
                t.column("from_healthkit", .boolean)
                t.column("created_at", .datetime)
                t.column("active_kcal", .double)
                t.column("total_kcal", .double)
                t.column("avg_hr", .double)
                t.column("effort", .double)
                t.column("session_id", .text)
                t.column("incline_pct", .double)
                t.column("elevation_m", .double)
                t.column("hk_uuid", .text)
            }
            try db.create(table: "personal_records") { t in
                t.column("user_id", .text).notNull()
                t.column("exercise_key", .text).notNull()
                t.column("axis", .text).notNull()
                t.column("value", .double).notNull()
                t.column("reps", .integer)
                t.column("weight_kg", .double)
                t.column("session_id", .text)
                t.column("achieved_on", .text).notNull()
                t.column("updated_at", .datetime)
                t.column("floor_value", .double)
                t.primaryKey(["user_id", "exercise_key", "axis"])
            }
            try db.create(table: "routine_templates") { t in
                t.column("user_id", .text).notNull()
                t.column("day_key", .text).notNull()
                t.column("payload", .text).notNull()
                t.column("source_session_id", .text)
                t.column("updated_at", .datetime).notNull()
                t.primaryKey(["user_id", "day_key"])
            }
            try db.create(table: "user_goals") { t in
                t.primaryKey("id", .text)
                t.column("user_id", .text).notNull()
                t.column("sleep_goal_hours", .double)
                t.column("calorie_goal", .integer)
                t.column("protein_goal_g", .integer)
                t.column("carbs_goal_g", .integer)
                t.column("fat_goal_g", .integer)
                t.column("steps_goal", .integer)
                t.column("active_cal_goal", .integer)
                t.column("water_goal_ml", .integer)
                t.column("context_mode", .text).notNull()
                t.column("goal_preset", .text)
                t.column("created_at", .datetime).notNull()
                t.column("updated_at", .datetime).notNull()
                t.column("auto_log_supplements", .boolean).notNull()
                t.column("active_program", .text).notNull()
                t.column("day_cutoff_hour", .integer).notNull()
                t.column("unit_system", .text).notNull()
                t.column("reduce_motion", .boolean).notNull()
                t.column("timezone", .text).notNull()
                t.column("target_weight_kg", .double)
                t.column("week_end_day", .integer)
                t.column("active_plan", .text)
                t.column("target_body_fat_pct", .double)
                t.column("target_muscle_mass_kg", .double)
                t.column("active_phase", .text)
                t.column("phase_started_on", .text)
                t.column("track_rpe", .boolean).notNull()
                t.column("active_lever", .text)
                t.column("context_since", .text)
                t.column("maintenance_until", .text)
            }
            try db.create(table: "target_profiles") { t in
                t.column("user_id", .text).notNull()
                t.column("key", .text).notNull()
                t.column("label", .text).notNull()
                t.column("summary", .text)
                t.column("sort", .integer).notNull()
                t.column("kcal", .integer)
                t.column("protein_g", .integer)
                t.column("carbs_g", .integer)
                t.column("fat_g", .integer)
                t.column("steps_goal", .integer)
                t.column("updated_at", .datetime).notNull()
                t.column("kind", .text)
                t.primaryKey(["user_id", "key"])
            }
            try db.create(table: "plans") { t in
                t.primaryKey("id", .text)
                t.column("user_id", .text).notNull()
                t.column("name", .text).notNull()
                t.column("program_id", .text)
                t.column("active", .boolean)
                t.column("started_on", .text)
                t.column("created_at", .datetime)
                t.column("blurb", .text)
                t.column("is_legacy", .boolean)
                t.column("sort", .integer)
            }
            try db.create(table: "plan_phase_goals") { t in
                t.column("user_id", .text).notNull()
                t.column("plan_id", .text).notNull()
                t.column("phase", .text).notNull()
                t.column("kcal", .integer)
                t.column("protein_g", .integer)
                t.column("carbs_g", .integer)
                t.column("fat_g", .integer)
                t.column("fiber_min", .integer)
                t.column("fiber_max", .integer)
                t.column("updated_at", .datetime)
                t.column("steps_goal", .integer)
                t.column("target_weight_kg", .double)
                t.column("target_body_fat_pct", .double)
                t.column("target_muscle_mass_kg", .double)
                t.column("rate_min_kg_wk", .double)
                t.column("rate_max_kg_wk", .double)
                t.column("label", .text)
                t.column("fiber_g", .integer)
                t.column("body_fat_ceiling_pct", .double)
                t.primaryKey(["user_id", "plan_id", "phase"])
            }
            try db.create(table: "plan_phase_volume") { t in
                t.column("user_id", .text).notNull()
                t.column("plan_id", .text).notNull()
                t.column("phase", .text).notNull()
                t.column("muscle", .text).notNull()
                t.column("target_sets", .integer).notNull()
                t.column("updated_at", .datetime)
                t.primaryKey(["user_id", "plan_id", "phase", "muscle"])
            }
            try db.create(table: "program_day_layout") { t in
                t.column("user_id", .text).notNull()
                t.column("program_id", .text).notNull()
                t.column("layout", .text).notNull()
                t.column("updated_at", .datetime).notNull()
                t.primaryKey(["user_id", "program_id"])
            }
            try db.create(table: "schedule_overrides") { t in
                t.column("user_id", .text).notNull()
                t.column("date", .text).notNull()
                t.column("day_key", .text).notNull()
                t.column("updated_at", .datetime).notNull()
                t.primaryKey(["user_id", "date"])
            }
            try db.create(table: "dashboard_layouts") { t in
                t.primaryKey("user_id", .text)
                t.column("layout", .text).notNull()
                t.column("updated_at", .datetime).notNull()
            }
            try db.create(table: "profiles") { t in
                t.primaryKey("user_id", .text)
                t.column("display_name", .text)
                t.column("role", .text).notNull()
                t.column("updated_at", .datetime).notNull()
                t.column("created_at", .datetime).notNull()
            }
            try db.create(table: "reports") { t in
                t.primaryKey("id", .text)
                t.column("user_id", .text).notNull()
                t.column("type", .text).notNull()
                t.column("period_start", .text).notNull()
                t.column("period_end", .text).notNull()
                t.column("content_md", .text)
                t.column("session_summary_md", .text)
                t.column("weight_report_md", .text)
                t.column("metrics", .text)
                t.column("notion_page_id", .text)
                t.column("created_at", .datetime).notNull()
            }
    }

    /// The tables added at `since: 2`, registered by `v21.genericModel`.
    static func migrateMirrorV2(_ db: Database) throws {
            try db.create(table: "stress_logs") { t in
                t.primaryKey("id", .text)
                t.column("user_id", .text).notNull()
                t.column("date", .text).notNull()
                t.column("slot", .text).notNull()
                t.column("level", .integer).notNull()
                t.column("tags", .text).notNull()
                t.column("note", .text)
                t.column("created_at", .datetime).notNull()
                t.column("updated_at", .datetime).notNull()
                t.column("logged_at", .datetime)
            }
            try db.create(table: "routines") { t in
                t.column("user_id", .text).notNull()
                t.column("program_id", .text).notNull()
                t.column("day_key", .text).notNull()
                t.column("label", .text).notNull()
                t.column("sub", .text)
                t.column("weekday", .integer).notNull()
                t.column("accent", .integer).notNull()
                t.column("sort", .integer).notNull()
                t.column("payload", .text).notNull()
                t.column("updated_at", .datetime).notNull()
                t.primaryKey(["user_id", "program_id", "day_key"])
            }
            try db.create(table: "plan_phases") { t in
                t.column("user_id", .text).notNull()
                t.column("plan_id", .text).notNull()
                t.column("start", .text).notNull()
                t.column("kind", .text).notNull()
                t.column("name", .text).notNull()
                t.column("short", .text)
                t.column("weeks", .integer).notNull()
                t.column("numbered", .boolean).notNull()
                t.column("first_week", .integer)
                t.column("era", .text)
                t.column("era_tag", .text)
                t.column("updated_at", .datetime).notNull()
                t.primaryKey(["user_id", "plan_id", "start"])
            }
            try db.create(table: "lever_periods") { t in
                t.column("user_id", .text).notNull()
                t.column("starts_on", .text).notNull()
                t.column("profile_key", .text)
                t.column("goals", .text)
                t.column("updated_at", .datetime).notNull()
                t.primaryKey(["user_id", "starts_on"])
            }
    }

    /// The tables added at `since: 3`, registered by `v33.prescriptions`.
    static func migrateMirrorV3(_ db: Database) throws {
            try db.create(table: "prescriptions") { t in
                t.primaryKey("id", .text)
                t.column("user_id", .text).notNull()
                t.column("exercise_key", .text).notNull()
                t.column("version", .integer).notNull()
                t.column("effective_from", .text).notNull()
                t.column("load_kg", .double)
                t.column("sets", .integer)
                t.column("rep_range", .text)
                t.column("rpe_cap", .double)
                t.column("structure", .text).notNull()
                t.column("set_loads", .text)
                t.column("lead_rule", .text).notNull()
                t.column("notes", .text)
                t.column("created_at", .datetime).notNull()
            }
    }
}

/// Every mirrored table, with the strategy that keeps it current.
///
/// Generated, so the list cannot fall behind the schema fixture the way a
/// hand-maintained one would. `bespoke` tables are absent on purpose: they
/// land in tables the logger already owns, through `SyncTranslation`.
///
/// `conflict` is the PostgREST upsert target for a LOCAL write of the table,
/// and it is the NATURAL key wherever one exists — introspected, not guessed.
/// Upserting `daily_logs` on `id` would insert a second row for a day the
/// server already holds under a different uuid, and then fail on
/// `daily_logs_user_id_date_key` forever.
public enum MirrorCatalogue {
    public static let tables: [MirrorTable] = [
        MirrorTable(name: "daily_logs", group: .daily, strategy: .delta(column: "updated_at"),
                    conflict: "user_id,date", order: ["id"],
                    pull: { try await $0.pull(DailyLogRow.self, from: $1) },
                    push: { try await $1.pushRow(DailyLogRow.self, from: $0, table: "daily_logs", conflict: "user_id,date", ref: $2) }),
        MirrorTable(name: "daily_metrics", group: .daily, strategy: .delta(column: "updated_at"),
                    conflict: "user_id,date", order: ["id"],
                    pull: { try await $0.pull(DailyMetricRow.self, from: $1) },
                    push: { try await $1.pushRow(DailyMetricRow.self, from: $0, table: "daily_metrics", conflict: "user_id,date", ref: $2) }),
        MirrorTable(name: "daily_scores", group: .daily, strategy: .window(column: "date"),
                    conflict: "user_id,date", order: ["id"],
                    pull: { try await $0.pull(DailyScoreRow.self, from: $1) },
                    push: { try await $1.pushRow(DailyScoreRow.self, from: $0, table: "daily_scores", conflict: "user_id,date", ref: $2) }),
        MirrorTable(name: "daily_targets", group: .daily, strategy: .delta(column: "updated_at"),
                    conflict: "user_id,date", order: ["user_id", "date"],
                    pull: { try await $0.pull(DailyTargetRow.self, from: $1) },
                    push: { try await $1.pushRow(DailyTargetRow.self, from: $0, table: "daily_targets", conflict: "user_id,date", ref: $2) }),
        MirrorTable(name: "nutrition_entries", group: .daily, strategy: .window(column: "date"),
                    conflict: "user_id,date,meal_type", order: ["id"],
                    pull: { try await $0.pull(NutritionEntryRow.self, from: $1) },
                    push: { try await $1.pushRow(NutritionEntryRow.self, from: $0, table: "nutrition_entries", conflict: "user_id,date,meal_type", ref: $2) }),
        MirrorTable(name: "water_intake", group: .daily, strategy: .window(column: "date"),
                    conflict: "id", order: ["id"],
                    pull: { try await $0.pull(WaterIntakeRow.self, from: $1) },
                    push: { try await $1.pushRow(WaterIntakeRow.self, from: $0, table: "water_intake", conflict: "id", ref: $2) }),
        MirrorTable(name: "supplement_log", group: .daily, strategy: .delta(column: "updated_at"),
                    conflict: "user_id,date,item_key", order: ["user_id", "date", "item_key"],
                    pull: { try await $0.pull(SupplementLogRow.self, from: $1) },
                    push: { try await $1.pushRow(SupplementLogRow.self, from: $0, table: "supplement_log", conflict: "user_id,date,item_key", ref: $2) }),
        MirrorTable(name: "custom_supplements", group: .daily, strategy: .full,
                    conflict: "id", order: ["id"],
                    pull: { try await $0.pull(CustomSupplementRow.self, from: $1) },
                    push: { try await $1.pushRow(CustomSupplementRow.self, from: $0, table: "custom_supplements", conflict: "id", ref: $2) }),
        MirrorTable(name: "fatigue_logs", group: .daily, strategy: .window(column: "date"),
                    conflict: "user_id,date,slot", order: ["id"],
                    pull: { try await $0.pull(FatigueLogRow.self, from: $1) },
                    push: { try await $1.pushRow(FatigueLogRow.self, from: $0, table: "fatigue_logs", conflict: "user_id,date,slot", ref: $2) }),
        MirrorTable(name: "stress_logs", group: .daily, strategy: .window(column: "date"),
                    conflict: "id", order: ["id"],
                    pull: { try await $0.pull(StressLogRow.self, from: $1) },
                    push: { try await $1.pushRow(StressLogRow.self, from: $0, table: "stress_logs", conflict: "id", ref: $2) }),
        MirrorTable(name: "doms_logs", group: .daily, strategy: .window(column: "date"),
                    conflict: "user_id,date,muscle_group,side,sub_region", order: ["id"],
                    pull: { try await $0.pull(DomsLogRow.self, from: $1) },
                    push: { try await $1.pushRow(DomsLogRow.self, from: $0, table: "doms_logs", conflict: "user_id,date,muscle_group,side,sub_region", ref: $2) }),
        MirrorTable(name: "body_composition", group: .body, strategy: .window(column: "date"),
                    conflict: "id", order: ["id"],
                    pull: { try await $0.pull(BodyCompositionRow.self, from: $1) },
                    push: { try await $1.pushRow(BodyCompositionRow.self, from: $0, table: "body_composition", conflict: "id", ref: $2) }),
        MirrorTable(name: "sleep_sessions", group: .body, strategy: .window(column: "start_time"),
                    conflict: "id", order: ["id"],
                    pull: { try await $0.pull(SleepSessionRow.self, from: $1) },
                    push: { try await $1.pushRow(SleepSessionRow.self, from: $0, table: "sleep_sessions", conflict: "id", ref: $2) }),
        MirrorTable(name: "cardio_logs", group: .body, strategy: .window(column: "date"),
                    conflict: "id", order: ["id"],
                    pull: { try await $0.pull(CardioLogRow.self, from: $1) },
                    push: { try await $1.pushRow(CardioLogRow.self, from: $0, table: "cardio_logs", conflict: "id", ref: $2) }),
        MirrorTable(name: "personal_records", group: .training, strategy: .delta(column: "updated_at"),
                    conflict: "user_id,exercise_key,axis", order: ["user_id", "exercise_key", "axis"],
                    pull: { try await $0.pull(PersonalRecordRow.self, from: $1) },
                    push: { try await $1.pushRow(PersonalRecordRow.self, from: $0, table: "personal_records", conflict: "user_id,exercise_key,axis", ref: $2) }),
        MirrorTable(name: "routine_templates", group: .training, strategy: .delta(column: "updated_at"),
                    conflict: "user_id,day_key", order: ["user_id", "day_key"],
                    pull: { try await $0.pull(RoutineTemplateRow.self, from: $1) },
                    push: { try await $1.pushRow(RoutineTemplateRow.self, from: $0, table: "routine_templates", conflict: "user_id,day_key", ref: $2) }),
        MirrorTable(name: "routines", group: .training, strategy: .delta(column: "updated_at"),
                    conflict: "user_id,program_id,day_key", order: ["user_id", "program_id", "day_key"],
                    pull: { try await $0.pull(RoutineRow.self, from: $1) },
                    push: { try await $1.pushRow(RoutineRow.self, from: $0, table: "routines", conflict: "user_id,program_id,day_key", ref: $2) }),
        MirrorTable(name: "user_goals", group: .plan, strategy: .delta(column: "updated_at"),
                    conflict: "user_id", order: ["id"],
                    pull: { try await $0.pull(UserGoalRow.self, from: $1) },
                    push: { try await $1.pushRow(UserGoalRow.self, from: $0, table: "user_goals", conflict: "user_id", ref: $2) }),
        MirrorTable(name: "target_profiles", group: .plan, strategy: .delta(column: "updated_at"),
                    conflict: "user_id,key", order: ["user_id", "key"],
                    pull: { try await $0.pull(TargetProfileRow.self, from: $1) },
                    push: { try await $1.pushRow(TargetProfileRow.self, from: $0, table: "target_profiles", conflict: "user_id,key", ref: $2) }),
        MirrorTable(name: "plans", group: .plan, strategy: .full,
                    conflict: "id", order: ["id"],
                    pull: { try await $0.pull(PlanRow.self, from: $1) },
                    push: { try await $1.pushRow(PlanRow.self, from: $0, table: "plans", conflict: "id", ref: $2) }),
        MirrorTable(name: "plan_phase_goals", group: .plan, strategy: .delta(column: "updated_at"),
                    conflict: "user_id,plan_id,phase", order: ["user_id", "plan_id", "phase"],
                    pull: { try await $0.pull(PlanPhaseGoalRow.self, from: $1) },
                    push: { try await $1.pushRow(PlanPhaseGoalRow.self, from: $0, table: "plan_phase_goals", conflict: "user_id,plan_id,phase", ref: $2) }),
        MirrorTable(name: "plan_phase_volume", group: .plan, strategy: .delta(column: "updated_at"),
                    conflict: "user_id,plan_id,phase,muscle", order: ["user_id", "plan_id", "phase", "muscle"],
                    pull: { try await $0.pull(PlanPhaseVolumeRow.self, from: $1) },
                    push: { try await $1.pushRow(PlanPhaseVolumeRow.self, from: $0, table: "plan_phase_volume", conflict: "user_id,plan_id,phase,muscle", ref: $2) }),
        MirrorTable(name: "program_day_layout", group: .plan, strategy: .delta(column: "updated_at"),
                    conflict: "user_id,program_id", order: ["user_id", "program_id"],
                    pull: { try await $0.pull(ProgramDayLayoutRow.self, from: $1) },
                    push: { try await $1.pushRow(ProgramDayLayoutRow.self, from: $0, table: "program_day_layout", conflict: "user_id,program_id", ref: $2) }),
        MirrorTable(name: "plan_phases", group: .plan, strategy: .full,
                    conflict: "user_id,plan_id,start", order: ["user_id", "plan_id", "start"],
                    pull: { try await $0.pull(PlanPhaseRow.self, from: $1) },
                    push: { try await $1.pushRow(PlanPhaseRow.self, from: $0, table: "plan_phases", conflict: "user_id,plan_id,start", ref: $2) }),
        MirrorTable(name: "lever_periods", group: .plan, strategy: .full,
                    conflict: "user_id,starts_on", order: ["user_id", "starts_on"],
                    pull: { try await $0.pull(LeverPeriodRow.self, from: $1) },
                    push: { try await $1.pushRow(LeverPeriodRow.self, from: $0, table: "lever_periods", conflict: "user_id,starts_on", ref: $2) }),
        MirrorTable(name: "schedule_overrides", group: .plan, strategy: .delta(column: "updated_at"),
                    conflict: "user_id,date", order: ["user_id", "date"],
                    pull: { try await $0.pull(ScheduleOverrideRow.self, from: $1) },
                    push: { try await $1.pushRow(ScheduleOverrideRow.self, from: $0, table: "schedule_overrides", conflict: "user_id,date", ref: $2) }),
        MirrorTable(name: "dashboard_layouts", group: .plan, strategy: .delta(column: "updated_at"),
                    conflict: "user_id", order: ["user_id"],
                    pull: { try await $0.pull(DashboardLayoutRow.self, from: $1) },
                    push: { try await $1.pushRow(DashboardLayoutRow.self, from: $0, table: "dashboard_layouts", conflict: "user_id", ref: $2) }),
        MirrorTable(name: "profiles", group: .plan, strategy: .delta(column: "updated_at"),
                    conflict: "user_id", order: ["user_id"],
                    pull: { try await $0.pull(ProfileRow.self, from: $1) },
                    push: { try await $1.pushRow(ProfileRow.self, from: $0, table: "profiles", conflict: "user_id", ref: $2) }),
        MirrorTable(name: "reports", group: .reports, strategy: .full,
                    conflict: "id", order: ["id"],
                    pull: { try await $0.pull(ReportRow.self, from: $1) },
                    push: { try await $1.pushRow(ReportRow.self, from: $0, table: "reports", conflict: "id", ref: $2) }),
        MirrorTable(name: "prescriptions", group: .training, strategy: .full,
                    conflict: "id", order: ["id"],
                    pull: { try await $0.pull(PrescriptionRow.self, from: $1) },
                    push: { try await $1.pushRow(PrescriptionRow.self, from: $0, table: "prescriptions", conflict: "id", ref: $2) }),
    ]

    /// By name. Every lookup the pusher and the realtime wiring do is by name,
    /// and rebuilding the dictionary per call would be a linear scan of
    /// twenty-six entries on the drain path.
    public static let byName: [String: MirrorTable] = Dictionary(
        tables.map { ($0.name, $0) }, uniquingKeysWith: { first, _ in first }
    )
}
